route:
  receiver: email-alert
  group_by: ['alertname', 'cluster']
  group_wait: 0s
  group_interval: 5s
  repeat_interval: 5s

receivers:
  - name: sms_team1
    email_configs:
      - to: 'abhijeetka@cybage.com'
