global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtp.mandrillapp.com:587'
  smtp_from: 'alert@alertnamager.com'
  smtp_auth_username: 'jefrycruz88@gmail.com'
  smtp_auth_password: 'w3-onjLmxEdpZm5BFtJRUQ'
route:
  receiver: email-alert
  group_by: ['alertname', 'cluster']
  group_wait: 5s
  group_interval: 1m
  repeat_interval: 1m

receivers:
  - name: email-alert
    email_configs:
      - to: EMAIL
